### ISSUE TITLE
Please deploy 0.0.2 to npm registry

### ISSUE THREAD

**Issue by ghost** [charles820/xunit-html-cov#2]
Hi - 

The latest version of xunit-html-cov on the npm registry is still 0.0.1.  Could you please deploy the current master version to the repo?  I don't mind doing it if you don't have time.

If you go here: https://registry.npmjs.org/xunit-html-cov you'll see that latest is still 0.0.1.

Thanks
Kevan

**Comment by charles820** [comment]
Thank you very very much. sorry i am late.
